### ISSUE TITLE
[Question] How to make datepicker larger? 

### ISSUE THREAD

**Issue by Kristian383** [mengxiong10/vue-datepicker-next#6]
**Vue-datepicker-next version**:
**Vue version**: 3
**Browser**: 

**Reproduction Link or Source Code**

Ive managed to change the width but is there already defined class so that content can be little bit bigger, also ive tried changing font size but it doesnt work? Ty

**Comment by mengxiong10** [comment]
It's a css problem, here is the easiest way
```css
.mx-datepicker-main {
    transform: scale(1.5);
    transform-origin: left top;
}

```
